#!/bin/bash

cp -R app build

cd build &&

git init &&
git remote add origin git@github.com:shiroyasha/randomGameOfLife.git &&
git add . --all &&
git commit -am "new version `date`" &&
git push origin master:gh-pages --force

rm -rm build
